### ISSUE TITLE
Set up project structure

### ISSUE THREAD

**Issue by lurldgbodex** [lurldgbodex/console-calculator#1]
## Description
Set up initial project structure using maven, including the basic directory structure (`src/main/java` and `src/test/java`) and add `pom.xml` file.

## Task

- [x] initialize a maven project
- [x] create necessary dependencies
- [x] set up `pom.xml` with necessary dependencies
- [x] push initial setup to the repository
