### ISSUE TITLE
[chore]: provide detailed readme

### ISSUE THREAD

**Issue by lurldgbodex** [lurldgbodex/console-calculator#2]
**Description**
 Write a comprehensive README file that outlines the project’s purpose, features, and setup instructions.

**Task**

- [ ] Write project overview and objectives.
- [ ] Document setup instructions.
- [ ] Outline the project structure.
- [ ] Include CI pipeline status badge
